server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://106.55.154.208:3306/m?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '#&Crz123321'
  jmx:
    enabled: false

mybatis-plus:
  mapper-locations: classpath:sqlMapperXml/*.xml
  type-aliases-package: com.crongze.model

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml